export const afroCelebrationForms = {
  Crafts: {
    CraftsmenandArtisans: [
      {
        label: "Craft Specialization",
        key: "craft_specialization",
        type: "text",
        required: true,
      },
      {
        label: "Biography",
        key: "biography",
        type: "textarea",
        required: false,
      },
      {
        label: "Portfolio",
        key: "portfolio",
        type: "textarea",
        required: false,
      },
      {
        label: "Awards and Recognitions",
        key: "awards_and_recognitions",
        type: "textarea",
        required: false,
      },
      { label: "Location", key: "location", type: "text", required: false },
      {
        label: "Contact Information",
        key: "contact_information",
        type: "text",
        required: false,
      },
      { label: "Media", key: "media", type: "file", required: false },
    ],
    CraftProjectsandCreations: [
      { label: "Title", key: "title", type: "text", required: true },
      {
        label: "Craft Specialization",
        key: "craft_specialization",
        type: "text",
        required: true,
      },
      {
        label: "Year Created",
        key: "year_created",
        type: "number",
        required: true,
      },
      {
        label: "Craftsman/Artisan",
        key: "craftsman_artisan",
        type: "select",
        options: [],
        required: true,
      },
      {
        label: "Description",
        key: "description",
        type: "textarea",
        required: true,
      },
      { label: "Location", key: "location", type: "text", required: false },
      { label: "Media", key: "media", type: "file", required: false },
    ],
    CraftWorkshopsandStudios: [
      { label: "Name", key: "name", type: "text", required: true },
      {
        label: "Craft Specialization",
        key: "craft_specialization",
        type: "text",
        required: true,
      },
      {
        label: "Description",
        key: "description",
        type: "textarea",
        required: true,
      },
      {
        label: "Notable Projects",
        key: "notable_projects",
        type: "textarea",
        required: true,
      },
      {
        label: "Contact Information",
        key: "contact_information",
        type: "text",
        required: true,
      },
      { label: "Location", key: "location", type: "text", required: true },
      { label: "Media", key: "media", type: "file", required: false },
    ],
    CraftFairsandMarkets: [
      { label: "Name", key: "name", type: "text", required: true },
      {
        label: "Year Established",
        key: "year_established",
        type: "number",
        required: true,
      },
      {
        label: "Description",
        key: "description",
        type: "textarea",
        required: false,
      },
      {
        label: "Upcoming Events",
        key: "upcoming_events",
        type: "textarea",
        required: false,
      },
      {
        label: "Participation Details",
        key: "participation_details",
        type: "textarea",
        required: true,
      },
      { label: "Location", key: "location", type: "text", required: true },
      { label: "Media", key: "media", type: "file", required: false },
    ],
    CraftEducationandTrainingInstitutions: [
      { label: "Name", key: "name", type: "text", required: true },
      {
        label: "Courses Offered",
        key: "courses_offered",
        type: "textarea",
        required: false,
      },
      {
        label: "Description",
        key: "description",
        type: "textarea",
        required: false,
      },
      {
        label: "Notable Alumni",
        key: "notable_alumni",
        type: "textarea",
        required: false,
      },
      { label: "Location", key: "location", type: "text", required: true },
      { label: "Media", key: "media", type: "file", required: false },
    ],
  },
  "Culinary Arts": {
    CulinaryProfessional: [
      {
        label: "Specialization",
        key: "specialization",
        type: "text",
        required: true,
      },
      {
        label: "Biography",
        key: "biography",
        type: "textarea",
        required: true,
      },
      {
        label: "Signature Dishes",
        key: "signature_dishes",
        type: "textarea",
        required: true,
      },
      {
        label: "Awards and Recognitions",
        key: "awards_and_recognitions",
        type: "textarea",
        required: false,
      },
      {
        label: "Contact Information",
        key: "contact_information",
        type: "text",
        required: true,
      },
      { label: "Location", key: "location", type: "text", required: true },
      { label: "Media", key: "media", type: "file", required: false },
    ],
    Restaurant: [
      { label: "Name", key: "name", type: "text", required: true },
      {
        label: "Cuisine Type",
        key: "cuisine_type",
        type: "text",
        required: true,
      },
      { label: "Menu", key: "menu", type: "textarea", required: true },
      {
        label: "Customer Reviews",
        key: "customer_reviews",
        type: "textarea",
        required: false,
      },
      {
        label: "Contact Information",
        key: "contact_information",
        type: "text",
        required: true,
      },
      { label: "Location", key: "location", type: "text", required: true },
      { label: "Media", key: "media", type: "file", required: false },
    ],
    CulinaryEvents: [
      { label: "Name", key: "name", type: "text", required: true },
      {
        label: "Year Established",
        key: "year_established",
        type: "number",
        required: true,
      },
      {
        label: "Description",
        key: "description",
        type: "textarea",
        required: true,
      },
      {
        label: "Upcoming Events",
        key: "upcoming_events",
        type: "textarea",
        required: false,
      },
      {
        label: "Participation Details",
        key: "participation_details",
        type: "textarea",
        required: false,
      },
      { label: "Location", key: "location", type: "text", required: true },
      { label: "Media", key: "media", type: "file", required: false },
    ],
    CulinarySchool: [
      { label: "Name", key: "name", type: "text", required: true },
      {
        label: "Courses Offered",
        key: "courses_offered",
        type: "textarea",
        required: true,
      },
      {
        label: "Description",
        key: "description",
        type: "textarea",
        required: true,
      },
      {
        label: "Notable Alumni",
        key: "notable_alumni",
        type: "textarea",
        required: false,
      },
      { label: "Location", key: "location", type: "text", required: true },
      { label: "Media", key: "media", type: "file", required: false },
    ],
  },
  "Design and Applied Art": {
    DesignersandArtists: [
      {
        label: "Specialization",
        key: "specialization",
        type: "text",
        required: true,
      },
      {
        label: "Biography",
        key: "biography",
        type: "textarea",
        required: true,
      },
      {
        label: "Portfolio",
        key: "portfolio",
        type: "textarea",
        required: true,
      },
      {
        label: "Awards and Recognitions",
        key: "awards_and_recognitions",
        type: "textarea",
        required: false,
      },
      { label: "Location", key: "location", type: "text", required: false },
      {
        label: "Contact Information",
        key: "contact_information",
        type: "text",
        required: true,
      },
      { label: "Media", key: "media", type: "file", required: false },
    ],
    DesignProjectsandArtWorks: [
      { label: "Title", key: "title", type: "text", required: true },
      {
        label: "Specialization",
        key: "specialization",
        type: "text",
        required: true,
      },
      {
        label: "Year Created",
        key: "year_created",
        type: "number",
        required: true,
      },
      {
        label: "Designer/Artist",
        key: "designer_or_artist",
        type: "select",
        options: [],
        required: true,
      },
      {
        label: "Description",
        key: "description",
        type: "textarea",
        required: false,
      },
      { label: "Location", key: "location", type: "text", required: false },
      { label: "Media", key: "media", type: "file", required: false },
    ],
    DesignStudiosandWorkPlaces: [
      { label: "Name", key: "name", type: "text", required: true },
      {
        label: "Specialization",
        key: "specialization",
        type: "text",
        required: true,
      },
      {
        label: "Description",
        key: "description",
        type: "textarea",
        required: true,
      },
      {
        label: "Notable Projects",
        key: "notable_projects",
        type: "textarea",
        required: false,
      },
      {
        label: "Contact Information",
        key: "contact_information",
        type: "text",
        required: true,
      },
      { label: "Location", key: "location", type: "text", required: true },
      { label: "Media", key: "media", type: "file", required: false },
    ],
    DesignandArtsExhibitions: [
      { label: "Name", key: "name", type: "text", required: true },
      {
        label: "Year Established",
        key: "year_established",
        type: "number",
        required: true,
      },
      {
        label: "Description",
        key: "description",
        type: "textarea",
        required: true,
      },
      {
        label: "Upcoming Events",
        key: "upcoming_events",
        type: "textarea",
        required: false,
      },
      {
        label: "Participation Details",
        key: "participation_details",
        type: "textarea",
        required: true,
      },
      { label: "Location", key: "location", type: "text", required: true },
      { label: "Media", key: "media", type: "file", required: false },
    ],
    DesignandArtsEducationandInstitutions: [
      { label: "Name", key: "name", type: "text", required: true },
      {
        label: "Courses Offered",
        key: "courses_offered",
        type: "textarea",
        required: true,
      },
      {
        label: "Description",
        key: "description",
        type: "textarea",
        required: true,
      },
      {
        label: "Notable Alumni",
        key: "notable_alumni",
        type: "textarea",
        required: false,
      },
      { label: "Location", key: "location", type: "text", required: true },
      { label: "Media", key: "media", type: "file", required: false },
    ],
  },
  "Digital and Multimedia": {
    DigitalandMultimediaArtists: [
      {
        label: "Specialization",
        key: "specialization",
        type: "text",
        required: true,
      },
      {
        label: "Biography",
        key: "biography",
        type: "textarea",
        required: true,
      },
      {
        label: "Portfolio",
        key: "portfolio",
        type: "textarea",
        required: true,
      },
      {
        label: "Awards and Recognitions",
        key: "awards_and_recognitions",
        type: "textarea",
        required: false,
      },
      {
        label: "Contact Information",
        key: "contact_information",
        type: "text",
        required: true,
      },
      { label: "Location", key: "location", type: "text", required: true },
      { label: "Media", key: "media", type: "file", required: false },
    ],
    DigitalandMultimediaProjects: [
      { label: "Title", key: "title", type: "text", required: true },
      {
        label: "Specialization",
        key: "specialization",
        type: "text",
        required: true,
      },
      {
        label: "Year Created",
        key: "year_created",
        type: "number",
        required: true,
      },
      {
        label: "Artist",
        key: "artist",
        type: "select",
        options: [],
        required: true,
      },
      {
        label: "Description",
        key: "description",
        type: "textarea",
        required: true,
      },
      { label: "Location", key: "location", type: "text", required: false },
      { label: "Media", key: "media", type: "file", required: false },
    ],
    DigitalandMultimediaStudios: [
      { label: "Name", key: "name", type: "text", required: true },
      {
        label: "Specialization",
        key: "specialization",
        type: "text",
        required: true,
      },
      {
        label: "Description",
        key: "description",
        type: "textarea",
        required: true,
      },
      {
        label: "Notable Projects",
        key: "notable_projects",
        type: "textarea",
        required: false,
      },
      {
        label: "Contact Information",
        key: "contact_information",
        type: "text",
        required: true,
      },
      { label: "Location", key: "location", type: "text", required: true },
      { label: "Media", key: "media", type: "file", required: false },
    ],
    DigitalandMultimediaExhibitionsandEvents: [
      { label: "Name", key: "name", type: "text", required: true },
      {
        label: "Year Established",
        key: "year_established",
        type: "number",
        required: true,
      },
      {
        label: "Description",
        key: "description",
        type: "textarea",
        required: true,
      },
      {
        label: "Upcoming Events",
        key: "upcoming_events",
        type: "textarea",
        required: false,
      },
      {
        label: "Participation Details",
        key: "participation_details",
        type: "textarea",
        required: true,
      },
      { label: "Location", key: "location", type: "text", required: true },
      { label: "Media", key: "media", type: "file", required: false },
    ],
    DigitalandMultimediaEducationandInstitutions: [
      { label: "Name", key: "name", type: "text", required: true },
      {
        label: "Courses Offered",
        key: "courses_offered",
        type: "textarea",
        required: true,
      },
      {
        label: "Description",
        key: "description",
        type: "textarea",
        required: true,
      },
      {
        label: "Notable Alumni",
        key: "notable_alumni",
        type: "textarea",
        required: false,
      },
      { label: "Location", key: "location", type: "text", required: true },
      { label: "Media", key: "media", type: "file", required: false },
    ],
  },
  "Environmental and Land Art": {
    EnvironmentalLandArtist: [
      {
        label: "Artistic Focus",
        key: "artisticFocus",
        type: "textarea",
        required: false,
      },
      {
        label: "Biography",
        key: "biography",
        type: "textarea",
        required: false,
      },
      {
        label: "Notable Works",
        key: "notableWorks",
        type: "textarea",
        required: false,
      },
      {
        label: "Exhibitions",
        key: "exhibitions",
        type: "textarea",
        required: false,
      },
      {
        label: "Contact Information",
        key: "contactInformation",
        type: "text",
        required: false,
      },
      { label: "Location", key: "location", type: "text", required: false },
      { label: "Media", key: "media", type: "file", required: false },
    ],
    EnvironmentalLandArtInstallation: [
      { label: "Title", key: "title", type: "text", required: true },
      {
        label: "Creation Date",
        key: "creationDate",
        type: "date",
        required: false,
      },
      {
        label: "Artist",
        key: "artist",
        type: "select",
        options: [],
        required: true,
      },
      {
        label: "Description",
        key: "description",
        type: "textarea",
        required: false,
      },
      {
        label: "Exhibition History",
        key: "exhibitionHistory",
        type: "textarea",
        required: false,
      },
      { label: "Location", key: "location", type: "text", required: true },
      { label: "Media", key: "media", type: "file", required: false },
    ],
    EnvironmentalLandArtSite: [
      { label: "Site Name", key: "siteName", type: "text", required: true },
      {
        label: "Description",
        key: "description",
        type: "textarea",
        required: false,
      },
      {
        label: "Artists and Works",
        key: "artistsAndWorks",
        type: "textarea",
        required: false,
      },
      {
        label: "Visiting Information",
        key: "visitingInformation",
        type: "textarea",
        required: false,
      },
      {
        label: "Contact Information",
        key: "contactInformation",
        type: "text",
        required: false,
      },
      { label: "Location", key: "location", type: "text", required: true },
      { label: "Media", key: "media", type: "file", required: false },
    ],
    EnvironmentalLandArtFestival: [
      { label: "Event Name", key: "eventName", type: "text", required: true },
      { label: "Date", type: "date", required: false },
      {
        label: "Description",
        key: "description",
        type: "textarea",
        required: false,
      },
      {
        label: "Upcoming Events",
        key: "upcomingEvents",
        type: "textarea",
        required: false,
      },
      {
        label: "Participation Details",
        key: "participationDetails",
        type: "textarea",
        required: false,
      },
      { label: "Location", key: "location", type: "text", required: true },
      { label: "Media", key: "media", type: "file", required: false },
    ],
  },
  "Experimental and Conceptual Art": {
    ExperimentalAndConceptualArtist: [
      {
        label: "Artistic Focus",
        key: "artistic_focus",
        type: "textarea",
        required: false,
      },
      {
        label: "Biography",
        key: "biography",
        type: "textarea",
        required: false,
      },
      {
        label: "Notable Works",
        key: "notable_works",
        type: "textarea",
        required: false,
      },
      {
        label: "Exhibitions",
        key: "exhibitions",
        type: "textarea",
        required: false,
      },
      {
        label: "Contact Information",
        key: "contact_information",
        type: "text",
        required: false,
      },
      { label: "Location", key: "location", type: "text", required: false },
      { label: "Media", key: "media", type: "file", required: false },
    ],
    ExperimentalAndConceptualArtInstallation: [
      { label: "Title", key: "title", type: "text", required: true },
      {
        label: "Creation Date",
        key: "creation_date",
        type: "date",
        required: true,
      },
      {
        label: "Artist",
        key: "artist",
        type: "select",
        options: [],
        required: true,
      },
      { label: "Concept", key: "concept", type: "textarea", required: false },
      {
        label: "Description",
        key: "description",
        type: "textarea",
        required: false,
      },
      {
        label: "Exhibition History",
        key: "exhibition_history",
        type: "textarea",
        required: false,
      },
      { label: "Location", key: "location", type: "text", required: false },
      { label: "Media", key: "media", type: "file", required: false },
    ],
    ExperimentalAndConceptualArtGalleries: [
      {
        label: "Gallery Name",
        key: "gallery_name",
        type: "text",
        required: true,
      },
      {
        label: "Exhibitions",
        key: "exhibitions",
        type: "textarea",
        required: false,
      },
      {
        label: "Featured Artists",
        key: "featured_artists",
        type: "text",
        required: false,
      },
      {
        label: "Contact Information",
        key: "contact_information",
        type: "text",
        required: false,
      },
      { label: "Location", key: "location", type: "text", required: false },
      { label: "Media", key: "media", type: "file", required: false },
    ],
    ExperimentalAndConceptualArtFestivalsAndEvents: [
      { label: "Event Name", key: "event_name", type: "text", required: true },
      { label: "Date", type: "date", required: false },
      {
        label: "Description",
        key: "description",
        type: "textarea",
        required: false,
      },
      {
        label: "Upcoming Events",
        key: "upcoming_events",
        type: "textarea",
        required: false,
      },
      {
        label: "Participation Details",
        key: "participation_details",
        type: "textarea",
        required: false,
      },
      { label: "Location", key: "location", type: "text", required: false },
      { label: "Media", key: "media", type: "file", required: false },
    ],
  },
  Extras: {
    Awards: [
      { label: "Name", key: "name", type: "text", required: true },
      { label: "Date", key: "date", type: "date", required: true },
      { label: "Media", key: "media", type: "file", required: false },
    ],
    AwardStatus: [
      { label: "Media", key: "media", type: "file", required: false },
      {
        label: "Award",
        key: "award",
        type: "select",
        options: [],
        required: true,
      },
      {
        label: "Status",
        key: "status",
        type: "select",
        options: ["Nominated", "Awarded"],
        required: true,
      },
    ],
    FilmAndMediaCourse: [
      { label: "Name", key: "name", type: "text", required: true },
      { label: "Duration", key: "duration", type: "text", required: true },
      { label: "Media", key: "media", type: "file", required: false },
    ],
  },
  "Film and Cinema": {
    Professional: [
      { label: "Profession", key: "profession", type: "text", required: true },
      {
        label: "Biography",
        key: "biography",
        type: "textarea",
        required: true,
      },
      {
        label: "Filmography",
        key: "filmography",
        type: "textarea",
        required: false,
      },
      { label: "Awards", key: "awards", type: "textarea", required: false },
      {
        label: "Profile Portfolio",
        key: "profile_portfolio",
        type: "file",
        required: false,
      },
      { label: "Location", key: "location", type: "text", required: false },
      { label: "Media", key: "media", type: "file", required: false },
    ],
    Film: [
      { label: "Title", key: "title", type: "text", required: true },
      {
        label: "Release Year",
        key: "release_year",
        type: "number",
        required: true,
      },
      {
        label: "Director",
        key: "director",
        type: "select",
        options: [],
        required: true,
      },
      {
        label: "Producers",
        key: "producers",
        type: "textarea",
        required: true,
      },
      {
        label: "Cast and Crew",
        key: "cast_and_crew",
        type: "textarea",
        required: true,
      },
      {
        label: "Plot Summary",
        key: "plot_summary",
        type: "textarea",
        required: true,
      },
      { label: "Awards", key: "awards", type: "textarea", required: false },
      { label: "Location", key: "location", type: "text", required: false },
      { label: "Media", key: "media", type: "file", required: false },
    ],
    FilmProductionCompany: [
      { label: "Name", key: "name", type: "text", required: true },
      {
        label: "Founding Year",
        key: "founding_Year",
        type: "number",
        required: true,
      },
      {
        label: "Description",
        key: "description",
        type: "textarea",
        required: true,
      },
      {
        label: "Notable Films",
        key: "notable_films",
        type: "textarea",
        required: true,
      },
      {
        label: "Contact Info",
        key: "contact_info",
        type: "textarea",
        required: true,
      },
      { label: "Location", key: "location", type: "text", required: true },
      { label: "Media", key: "media", type: "file", required: false },
    ],
    FilmFestival: [
      { label: "Name", key: "name", type: "text", required: true },
      {
        label: "Year Established",
        key: "year_established",
        type: "number",
        required: true,
      },
      {
        label: "Description",
        key: "description",
        type: "textarea",
        required: true,
      },
      {
        label: "Submission Details",
        key: "submissionDetails",
        type: "textarea",
        required: true,
      },
      { label: "Location", key: "location", type: "text", required: true },
      { label: "Media", key: "media", type: "file", required: false },
    ],
    FilmSchool: [
      { label: "Name", key: "name", type: "text", required: true },
      {
        label: "Courses Offered",
        key: "coursesOffered",
        type: "textarea",
        required: true,
      },
      {
        label: "Description",
        key: "description",
        type: "textarea",
        required: true,
      },
      { label: "Alumni", key: "alumni", type: "text", required: true },
      { label: "Location", key: "location", type: "text", required: true },
      { label: "Media", key: "media", type: "file", required: false },
    ],
  },
  "Heritage and Tourism": {
    HeritageSitesAndMonuments: [
      { label: "Site Name", key: "site_name", type: "text", required: true },
      { label: "Location", key: "location", type: "text", required: false },
      {
        label: "Description",
        key: "description",
        type: "textarea",
        required: false,
      },
      {
        label: "Cultural Significance",
        key: "cultural_significance",
        type: "textarea",
        required: false,
      },
      {
        label: "Visiting Information",
        key: "visiting_information",
        type: "textarea",
        required: false,
      },
      {
        label: "Contact Information",
        key: "contact_information",
        type: "text",
        required: false,
      },
      { label: "Media", key: "media", type: "file", required: false },
    ],
    TourismProfessional: [
      { label: "Occupation", key: "occupation", type: "text", required: false },
      {
        label: "Biography",
        key: "biography",
        type: "textarea",
        required: false,
      },
      {
        label: "Expertise",
        key: "expertise",
        type: "textarea",
        required: false,
      },
      { label: "Location", key: "location", type: "text", required: false },
      {
        label: "Contact Information",
        key: "contact_information",
        type: "text",
        required: false,
      },
      { label: "Media", key: "media", type: "file", required: false },
    ],
    MuseumsAndCulturalInstitutions: [
      { label: "Name", key: "name", type: "text", required: true },
      { label: "Type", key: "type", type: "text", required: false },
      { label: "Location", key: "location", type: "text", required: false },
      {
        label: "Collections",
        key: "collections",
        type: "textarea",
        required: false,
      },
      {
        label: "Visitor Information",
        key: "visitor_information",
        type: "textarea",
        required: false,
      },
      {
        label: "Contact Information",
        key: "contact_information",
        type: "text",
        required: false,
      },
      { label: "Media", key: "media", type: "file", required: false },
    ],
    TourismEventsAndFestivals: [
      { label: "Event Name", key: "event_name", type: "text", required: true },
      { label: "Location", key: "location", type: "text", required: true },
      { label: "Date", key: "date", type: "date", required: false },
      {
        label: "Description",
        key: "description",
        type: "textarea",
        required: false,
      },
      {
        label: "Upcoming Events",
        key: "upcoming_events",
        type: "multi-date",
        required: false,
      },
      {
        label: "Participation Details",
        key: "participation_details",
        type: "textarea",
        required: false,
      },
      { label: "Media", key: "media", type: "file", required: false },
    ],
  },
  "Literary Arts": {
    WritersAndAuthors: [
      { label: "Genres", key: "genres", type: "text", required: false },
      {
        label: "Biography",
        key: "biography",
        type: "textarea",
        required: false,
      },
      {
        label: "Notable Works",
        key: "notable_works",
        type: "textarea",
        required: false,
      },
      {
        label: "Awards and Recognitions",
        key: "awardsAndRecognitions",
        type: "textarea",
        required: false,
      },
      { label: "Latitude", key: "latitude", type: "text", required: false },
      { label: "Longitude", key: "longitude", type: "text", required: false },
      { label: "Media", key: "media", type: "file", required: false },
    ],
    LiteraryWorks: [
      { label: "Title", key: "title", type: "text", required: true },
      { label: "Genre", key: "genre", type: "text", required: false },
      {
        label: "Year Published",
        key: "yearPublished",
        type: "number",
        required: false,
      },
      {
        label: "Author",
        key: "authorName",
        type: "select",
        options: [],
        required: true,
      },
      { label: "Synopsis", key: "synopsis", type: "textarea", required: false },
      { label: "Latitude", key: "latitude", type: "text", required: false },
      { label: "Longitude", key: "longitude", type: "text", required: false },
      { label: "Media", key: "media", type: "file", required: false },
    ],
    PublishingHouses: [
      { label: "Name", key: "name", type: "text", required: true },
      { label: "Location", key: "location", type: "text", required: false },
      {
        label: "Description",
        key: "description",
        type: "textarea",
        required: false,
      },
      {
        label: "Notable Publications",
        key: "notablePublications",
        type: "textarea",
        required: false,
      },
      {
        label: "Contact Information",
        key: "contactInformation",
        type: "textarea",
        required: false,
      },
      { label: "Latitude", key: "latitude", type: "text", required: false },
      { label: "Longitude", key: "longitude", type: "text", required: false },
      { label: "Media", key: "media", type: "file", required: false },
    ],
    LiteraryFestivalAndEvents: [
      { label: "Name", key: "name", type: "text", required: true },
      { label: "Location", key: "location", type: "text", required: false },
      {
        label: "Year Established",
        key: "yearEstablished",
        type: "number",
        required: false,
      },
      {
        label: "Description",
        key: "description",
        type: "textarea",
        required: false,
      },
      {
        label: "Participation Details",
        key: "participationDetails",
        type: "textarea",
        required: false,
      },
      { label: "Latitude", key: "latitude", type: "text", required: false },
      { label: "Longitude", key: "longitude", type: "text", required: false },
      { label: "Media", key: "media", type: "file", required: false },
    ],
    LiteraryEducationAndInstitutions: [
      { label: "Name", key: "name", type: "text", required: true },
      { label: "Location", key: "location", type: "text", required: false },
      {
        label: "Courses Offered",
        key: "coursesOffered",
        type: "textarea",
        required: false,
      },
      {
        label: "Description",
        key: "description",
        type: "textarea",
        required: false,
      },
      {
        label: "Notable Alumni",
        key: "notableAlumni",
        type: "textarea",
        required: false,
      },
      { label: "Latitude", key: "latitude", type: "text", required: false },
      { label: "Longitude", key: "longitude", type: "text", required: false },
      { label: "Media", key: "media", type: "file", required: false },
    ],
  },
  "Martial and Physical Arts": {
    MartialArtsInstructor: [
      {
        label: "Specialization",
        key: "specialization",
        type: "text",
        required: true,
      },
      {
        label: "Biography",
        key: "biography",
        type: "textarea",
        required: true,
      },
      {
        label: "Training Programs",
        key: "training_programs",
        type: "textarea",
        required: true,
      },
      {
        label: "Certifications",
        key: "certifications",
        type: "textarea",
        required: false,
      },
      { label: "Location", key: "location", type: "text", required: false },
      {
        label: "Contact Information",
        key: "contact_information",
        type: "text",
        required: true,
      },
      { label: "Media", key: "media", type: "file", required: false },
    ],
    MartialArtsSchool: [
      { label: "Name", key: "name", type: "text", required: true },
      { label: "Discipline", key: "discipline", type: "text", required: true },
      { label: "Latitude", key: "latitude", type: "text", required: false },
      { label: "Longitude", key: "longitude", type: "text", required: false },
      { label: "Programs", type: "textarea", required: true },
      {
        label: "Contact Information",
        key: "contact_information",
        type: "text",
        required: true,
      },
      { label: "Media", key: "media", type: "file", required: false },
    ],
    MartialArtsCompetition: [
      { label: "Event Name", key: "event_name", type: "text", required: true },
      { label: "Location", key: "location", type: "text", required: false },
      { label: "Date", key: "date", type: "date", required: true },
      {
        label: "Description",
        key: "description",
        type: "textarea",
        required: true,
      },
      {
        label: "Upcoming Events",
        key: "upcoming_events",
        type: "textarea",
        required: false,
      },
      {
        label: "Registration Details",
        key: "registration_details",
        type: "textarea",
        required: false,
      },
      { label: "Media", key: "media", type: "file", required: false },
    ],
    MartialArtsTrainingCenter: [
      { label: "Name", key: "name", type: "text", required: true },
      { label: "Focus", key: "focus", type: "text", required: true },
      { label: "Location", key: "location", type: "text", required: false },
      {
        label: "Facility Description",
        key: "facility_description",
        type: "textarea",
        required: true,
      },
      {
        label: "Training Programs",
        key: "training_programs",
        type: "textarea",
        required: true,
      },
      {
        label: "Contact Information",
        key: "contact_information",
        type: "text",
        required: true,
      },
      { label: "Media", key: "media", type: "file", required: false },
    ],
  },
  "Music Industry": {
    MusiciansandArtists: [
      { label: "Genres", key: "genres", type: "text", required: true },
      {
        label: "Biography",
        key: "biography",
        type: "textarea",
        required: true,
      },
      {
        label: "Discography",
        key: "discography",
        type: "textarea",
        required: true,
      },
      {
        label: "Awards and Recognitions",
        key: "awards_and_recognitions",
        type: "textarea",
        required: false,
      },
      { label: "Media", key: "media", type: "file", required: false },
    ],
    AlbumsandMusicReleases: [
      { label: "Title", key: "title", type: "text", required: true },
      { label: "Genre", key: "genre", type: "text", required: true },
      {
        label: "Year Released",
        key: "year_released",
        type: "number",
        required: true,
      },
      {
        label: "Artist",
        key: "artist",
        type: "select",
        options: [],
        required: true,
      },
      {
        label: "Tracklist",
        key: "tracklist",
        type: "textarea",
        required: false,
      },
      {
        label: "Description",
        key: "description",
        type: "textarea",
        required: false,
      },
      { label: "Media", key: "media", type: "file", required: false },
    ],
    MusicProductionStudios: [
      { label: "Name", key: "name", type: "text", required: true },
      { label: "Location", key: "location", type: "text", required: true },
      {
        label: "Description",
        key: "description",
        type: "textarea",
        required: true,
      },
      {
        label: "Notable Projects",
        key: "notable_projects",
        type: "textarea",
        required: true,
      },
      {
        label: "Contact Information",
        key: "contact_information",
        type: "text",
        required: true,
      },
      { label: "Latitude", key: "latitude", type: "number", required: true },
      { label: "Longitude", key: "longitude", type: "number", required: true },
      { label: "Media", key: "media", type: "file", required: false },
    ],
    MusicVenuesandConcertHalls: [
      { label: "Name", key: "name", type: "text", required: true },
      { label: "Location", key: "location", type: "text", required: true },
      {
        label: "Description",
        key: "description",
        type: "textarea",
        required: false,
      },
      {
        label: "Upcoming Shows",
        key: "upcoming_shows",
        type: "textarea",
        required: false,
      },
      {
        label: "Contact Information",
        key: "contact_information",
        type: "text",
        required: false,
      },
      { label: "Media", key: "media", type: "file", required: false },
    ],
    MusicFestivalsandEvents: [
      { label: "Name", key: "name", type: "text", required: true },
      { label: "Location", key: "location", type: "text", required: true },
      {
        label: "Year Established",
        key: "year_established",
        type: "number",
        required: true,
      },
      {
        label: "Description",
        key: "description",
        type: "textarea",
        required: false,
      },
      {
        label: "Participation Details",
        key: "participation_details",
        type: "textarea",
        required: false,
      },
      { label: "Media", key: "media", type: "file", required: false },
    ],
    MusicEducationandInstitutions: [
      { label: "Name", key: "name", type: "text", required: true },
      { label: "Location", key: "location", type: "text", required: true },
      {
        label: "Courses Offered",
        key: "courses_offered",
        type: "textarea",
        required: false,
      },
      {
        label: "Description",
        key: "description",
        type: "textarea",
        required: false,
      },
      {
        label: "Notable Alumni",
        key: "notable_alumni",
        type: "textarea",
        required: false,
      },
      { label: "Media", key: "media", type: "file", required: false },
    ],
  },
  "Performing Arts": {
    Performers: [
      { label: "Art Form", key: "artForm", type: "text", required: true },
      {
        label: "Biography",
        key: "biography",
        type: "textarea",
        required: false,
      },
      {
        label: "Repertoire",
        key: "repertoire",
        type: "textarea",
        required: false,
      },
      {
        label: "Awards and Recognitions",
        key: "awardsAndRecognitions",
        type: "textarea",
        required: false,
      },
      { label: "Latitude", key: "latitude", type: "text", required: false },
      { label: "Longitude", key: "longitude", type: "text", required: false },
      { label: "Media", key: "media", type: "file", required: false },
    ],
    TheaterProfessionals: [
      { label: "Occupation", type: "text", required: true },
      {
        label: "Biography",
        key: "biography",
        type: "textarea",
        required: false,
      },
      {
        label: "Notable Works",
        key: "notable_works",
        type: "textarea",
        required: false,
      },
      {
        label: "Awards and Recognitions",
        key: "awards_and_recognitions",
        type: "textarea",
        required: false,
      },
      { label: "Location", key: "location", type: "text", required: false },
      {
        label: "Contact Information",
        key: "contact_information",
        type: "text",
        required: false,
      },
      { label: "Media", key: "media", type: "file", required: false },
    ],
    PerformancesAndProductions: [
      { label: "Title", key: "title", type: "text", required: true },
      { label: "Art Form", type: "text", required: true },
      { label: "Year", type: "number", required: true },
      {
        label: "Description",
        key: "description",
        type: "textarea",
        required: false,
      },
      { label: "Latitude", key: "latitude", type: "text", required: false },
      { label: "Longitude", key: "longitude", type: "text", required: false },
      {
        label: "Director",
        key: "director",
        type: "select",
        options: [],
        required: false,
      },
      { label: "Performer", type: "select", options: [], required: false },
      { label: "Media", key: "media", type: "file", required: false },
    ],
    VenuesAndTheaters: [
      { label: "Name", key: "name", type: "text", required: true },
      { label: "Location", key: "location", type: "text", required: true },
      {
        label: "Description",
        key: "description",
        type: "textarea",
        required: false,
      },
      { label: "Upcoming Shows", type: "textarea", required: false },
      {
        label: "Contact Information",
        key: "contact_information",
        type: "text",
        required: false,
      },
      { label: "Latitude", key: "latitude", type: "text", required: false },
      { label: "Longitude", key: "longitude", type: "text", required: false },
      { label: "Media", key: "media", type: "file", required: false },
    ],
    PerformingArtsAndFestivals: [
      { label: "Name", key: "name", type: "text", required: true },
      { label: "Location", key: "location", type: "text", required: true },
      {
        label: "Year Established",
        key: "year_established",
        type: "number",
        required: false,
      },
      {
        label: "Description",
        key: "description",
        type: "textarea",
        required: false,
      },
      {
        label: "Participation Details",
        key: "participation_details",
        type: "textarea",
        required: false,
      },
      { label: "Latitude", key: "latitude", type: "text", required: false },
      { label: "Longitude", key: "longitude", type: "text", required: false },
      { label: "Media", key: "media", type: "file", required: false },
    ],
    PerformingArtsSchoolsAndTrainingInstitutions: [
      { label: "Name", key: "name", type: "text", required: true },
      { label: "Location", key: "location", type: "text", required: true },
      {
        label: "Courses Offered",
        key: "courses_offered",
        type: "textarea",
        required: false,
      },
      {
        label: "Description",
        key: "description",
        type: "textarea",
        required: false,
      },
      {
        label: "Notable Alumni",
        key: "notable_alumni",
        type: "textarea",
        required: false,
      },
      { label: "Latitude", key: "latitude", type: "text", required: false },
      { label: "Longitude", key: "longitude", type: "text", required: false },
      { label: "Media", key: "media", type: "file", required: false },
    ],
  },
  "Street and Graffiti Art": {
    StreetGraffitiArtist: [
      {
        label: "Specialization",
        key: "specialization",
        type: "text",
        required: true,
      },
      {
        label: "Biography",
        key: "biography",
        type: "textarea",
        required: true,
      },
      {
        label: "Portfolio",
        key: "portfolio",
        type: "textarea",
        required: true,
      },
      {
        label: "Recognition",
        key: "recognition",
        type: "textarea",
        required: false,
      },
      { label: "Location", key: "location", type: "text", required: true },
      {
        label: "Contact Information",
        key: "contact_information",
        type: "text",
        required: true,
      },
      { label: "Media", key: "media", type: "file", required: false },
    ],
    StreetGraffitiWork: [
      { label: "Title", key: "title", type: "text", required: true },
      { label: "Media", key: "media", type: "file", required: false },
      { label: "Type", key: "type", type: "text", required: true },
      {
        label: "Year Created",
        key: "year_created",
        type: "number",
        required: true,
      },
      {
        label: "Artist",
        key: "artist",
        type: "select",
        options: [],
        required: true,
      },
      {
        label: "Description",
        key: "description",
        type: "textarea",
        required: true,
      },
      { label: "Location", key: "location", type: "text", required: true },
    ],
    StreetGraffitiMural: [
      { label: "Title", key: "title", type: "text", required: true },
      { label: "Artist", key: "artist", type: "select", options: [], required: true },
      { label: "Location", key: "location", type: "text", required: true },
      {
        label: "Description",
        key: "description",
        type: "textarea",
        required: true,
      },
      { label: "Recognition", key: "recognition", type: "textarea", required: false },
      {
        label: "Contact Information",
        key: "contact_information",
        type: "text",
        required: false,
      },
      { label: "Media", key: "media", type: "file", required: false },
    ],
    StreetGraffitiEvent: [
      { label: "Name", key: "name", type: "text", required: true },
      { label: "Location", key: "location", type: "text", required: true },
      {
        label: "Year Established",
        key: "year_established",
        type: "number",
        required: true,
      },
      {
        label: "Description",
        key: "description",
        type: "textarea",
        required: true,
      },
      {
        label: "Upcoming Events",
        key: "upcoming_events",
        type: "textarea",
        required: false,
      },
      {
        label: "Participation Details",
        key: "participation_details",
        type: "textarea",
        required: false,
      },
      { label: "Media", key: "media", type: "file", required: false },
    ],
  },
  "Visual Art": {
    Artists: [
      { label: "Art Medium", key: "artMedium", type: "text", required: true },
      {
        label: "Biography",
        key: "biography",
        type: "textarea",
        required: false,
      },
      { label: "Latitude", key: "latitude", type: "text", required: false },
      { label: "Longitude", key: "longitude", type: "text", required: false },
      { label: "Media", key: "media", type: "file", required: false },
    ],
    Artworks: [
      { label: "Title", key: "title", type: "text", required: true },
      { label: "Art Medium", key: "artMedium", type: "text", required: true },
      {
        label: "Year Created",
        key: "yearCreated",
        type: "number",
        required: true,
      },
      { label: "Artist", key: "artist", type: "select", required: true, options: [] },
      {
        label: "Description",
        key: "description",
        type: "textarea",
        required: false,
      },
      { label: "Media", key: "media", type: "file", required: false },
    ],
    ArtGalleriesAndMuseums: [
      { label: "Name", key: "name", type: "text", required: true },
      { label: "Location", key: "location", type: "text", required: true },
      {
        label: "Description",
        key: "description",
        type: "textarea",
        required: false,
      },
      { label: "Notable Exhibitions", key: "notableExhibitions", type: "textarea", required: false },
      {
        label: "Contact Information",
        key: "contactInformation",
        type: "text",
        required: false,
      },
      { label: "Latitude", key: "latitude", type: "text", required: false },
      { label: "Longitude", key: "longitude", type: "text", required: false },
      { label: "Media", key: "media", type: "file", required: false },
    ],
    ArtEventsAndFestivals: [
      { label: "Name", key: "name", type: "text", required: true },
      { label: "Location", key: "location", type: "text", required: true },
      {
        label: "Year Established",
        key: "yearEstablished",
        type: "number",
        required: true,
      },
      {
        label: "Description",
        key: "description",
        type: "textarea",
        required: false,
      },
      {
        label: "Participation Details",
        key: "participationDetails",
        type: "textarea",
        required: false,
      },
      { label: "Latitude", key: "latitude", type: "text", required: false },
      { label: "Longitude", key: "longitude", type: "text", required: false },
      { label: "Media", key: "media", type: "file", required: false },
    ],
    ArtEducationAndInstitutions: [
      { label: "Media", key: "media", type: "file", required: false },
      { label: "Name", key: "name", type: "text", required: true },
      { label: "Location", key: "location", type: "text", required: true },
      {
        label: "Courses Offered",
        key: "coursesOffered",
        type: "textarea",
        required: false,
      },
      {
        label: "Description",
        key: "description",
        type: "textarea",
        required: false,
      },
      {
        label: "Notable Alumni",
        key: "notableAlumni",
        type: "textarea",
        required: false,
      },
      { label: "Latitude", key: "latitude", type: "text", required: false },
      { label: "Longitude", key: "longitude", type: "text", required: false },
    ],
  },
};
