export const culturalMappingForms = {
  "Community and Cultural Organizations": {
    CulturalCommunityOrganizations: [
      {
        label: "Activity Name",
        key: "activity_name",
        type: "text",
        required: true,
      },
      { label: "Location", key: "location", type: "text", required: true },
      {
        label: "Mission and Goals",
        key: "mission_and_goals",
        type: "textarea",
        required: true,
      },
      {
        label: "Activities and Programs",
        key: "activities_and_programs",
        type: "textarea",
        required: true,
      },
      {
        label: "Contact Information",
        key: "contact_information",
        type: "text",
        required: true,
      },
      { label: "Media", key: "media", type: "file", required: false },
    ],
    CulturalWorkshopsAndClasses: [
      { label: "Name", key: "workshop_name", type: "text", required: true },
      { label: "Location", key: "location", type: "text", required: true }, // Similar to location in other model
      {
        label: "Description",
        key: "description",
        type: "textarea",
        required: true,
      },
      { label: "Schedule", key: "schedule", type: "textarea", required: true },
      {
        label: "Instructors",
        key: "instructors",
        type: "textarea",
        required: true,
      },
      {
        label: "Contact Information",
        key: "contact_information",
        type: "text",
        required: true,
      },
      { label: "Media", key: "media", type: "file", required: false },
    ],
    CommunityArtInstallations: [
      {
        label: "Installation Name",
        key: "installation_name",
        type: "text",
        required: true,
      },
      { label: "Location", key: "location", type: "text", required: true },
      {
        label: "Description",
        key: "description",
        type: "textarea",
        required: true,
      },
      { label: "Artists", key: "artists", type: "textarea", required: true },
      {
        label: "Public Viewing Information",
        key: "public_viewing_information",
        type: "textarea",
        required: true,
      },
      {
        label: "Contact Information",
        key: "contact_information",
        type: "text",
        required: true,
      },
      { label: "Media", key: "media", type: "file", required: false },
    ],
  },
  "Creative and Cultural Occupation": {
    CreativeProfessionals: [
      { label: "Occupation", key: "occupation", type: "text", required: false },
      {
        label: "Biography",
        key: "biography",
        type: "textarea",
        required: false,
      },
      {
        label: "Expertise",
        key: "expertise",
        type: "textarea",
        required: false,
      },
      { label: "Location", key: "location", type: "text", required: false },
      {
        label: "Contact Information",
        key: "contactInformation",
        type: "text",
        required: false,
      },
      { label: "Media", key: "media", type: "file", required: false },
    ],
    CreativeStudiosAndWorkspaces: [
      { label: "Studio Name", key: "studioName", type: "text", required: true },
      { label: "Type", key: "type", type: "text", required: false },
      { label: "Location", key: "location", type: "text", required: false },
      {
        label: "Facilities",
        key: "facilities",
        type: "textarea",
        required: false,
      },
      {
        label: "Services Offered",
        key: "servicesOffered",
        type: "textarea",
        required: false,
      },
      {
        label: "Contact Information",
        key: "contactInformation",
        type: "text",
        required: false,
      },
      { label: "Media", key: "media", type: "file", required: false },
    ],
    CreativeEventsAndPerfomances: [
      { label: "Name", key: "eventName", type: "text", required: true },
      { label: "Location", key: "location", type: "text", required: true },
      { label: "Date", type: "date", required: false },
      {
        label: "Description",
        key: "description",
        type: "textarea",
        required: false,
      },
      {
        label: "Upcoming Events",
        key: "upcomingEvents",
        type: "textarea",
        required: false,
      },
      {
        label: "Contact Information",
        key: "contactInformation",
        type: "text",
        required: false,
      },
      { label: "Media", key: "media", type: "file", required: false },
    ],
  },
  "Cultural Events/Festivals and Ceremonies": {
    CulturalEventsFestival: [
      { label: "Name", key: "eventName", type: "text", required: true },
      { label: "Location", key: "location", type: "text", required: false },
      { label: "Date", type: "date", required: false },
      {
        label: "Description",
        key: "description",
        type: "textarea",
        required: false,
      },
      {
        label: "Participation Details",
        key: "participationDetails",
        type: "textarea",
        required: false,
      },
      {
        label: "Contact Information",
        key: "contactInformation",
        type: "text",
        required: false,
      },
      { label: "Media", key: "media", type: "file", required: false },
    ],
    TraditionalCeremonies: [
      {
        label: "Ceremony Name",
        key: "ceremonyName",
        type: "text",
        required: true,
      },
      { label: "Location", key: "location", type: "text", required: false },
      { label: "Date", type: "date", required: false },
      {
        label: "Description",
        key: "description",
        type: "textarea",
        required: false,
      },
      {
        label: "Participants",
        key: "participants",
        type: "textarea",
        required: false,
      },
      {
        label: "Contact Information",
        key: "contactInformation",
        type: "text",
        required: false,
      },
      { label: "Media", key: "media", type: "file", required: false },
    ],
    CulturalParadesAndProcessions: [
      { label: "Name", key: "paradeName", type: "text", required: true },
      { label: "Location", key: "location", type: "text", required: false },
      { label: "Date", type: "date", required: false },
      {
        label: "Description",
        key: "description",
        type: "textarea",
        required: false,
      },
      { label: "Route Map", key: "routeMap", type: "file", required: false },
      {
        label: "Contact Information",
        key: "contactInformation",
        type: "text",
        required: false,
      },
      { label: "Media", key: "media", type: "file", required: false },
    ],
    MusicAndDancePerfomance: [
      {
        label: "Performance Name",
        key: "perfomanceName",
        type: "text",
        required: true,
      },
      { label: "Location", key: "location", type: "text", required: false },
      { label: "Date", key: "date", type: "date", required: false },
      {
        label: "Description",
        key: "description",
        type: "textarea",
        required: false,
      },
      {
        label: "Performers",
        key: "performers",
        type: "textarea",
        required: false,
      },
      {
        label: "Contact Information",
        key: "contactInformation",
        type: "text",
        required: false,
      },
      { label: "Media", key: "media", type: "file", required: false },
    ],
  },
  "Cultural Industries": {
    CulturalOrganization: [
      {
        label: "Organization Name",
        key: "organizationName",
        type: "text",
        required: true,
      },
      { label: "Type", key: "type", type: "text", required: false },
      { label: "Location", key: "location", type: "text", required: false },
      { label: "Mission", key: "mission", type: "textarea", required: false },
      { label: "Services", key: "services", type: "textarea", required: false },
      {
        label: "Contact Information",
        key: "contactInformation",
        type: "text",
        required: false,
      },
      { label: "Media", key: "media", type: "file", required: false },
    ],
  },
  "Heritage Places": {
    HeritageSites: [
      { label: "Site Name", key: "site_name", type: "text", required: true },
      { label: "Type", key: "type", type: "text", required: true },
      { label: "Location", key: "location", type: "text", required: true },
      {
        label: "Description",
        key: "description",
        type: "textarea",
        required: true,
      },
      {
        label: "Visiting Hours",
        keys: "visiting_hours",
        type: "textarea",
        required: true,
      },
      {
        label: "Contact Information",
        key: "contact_information",
        type: "text",
        required: true,
      },
      { label: "Media", key: "media", type: "file", required: false },
    ],
    HistoricLandmarks: [
      {
        label: "Landmark Name",
        key: "landmark_name",
        type: "text",
        required: true,
      },
      { label: "Location", key: "location", type: "text", required: true },
      {
        label: "Description",
        key: "description",
        type: "textarea",
        required: true,
      },
      {
        label: "Architectural Style",
        key: "architectural_style",
        type: "textarea",
        required: true,
      },
      {
        label: "Public Access",
        key: "public_access",
        type: "textarea",
        required: true,
      },
      {
        label: "Contact Information",
        key: "contact_information",
        type: "text",
        required: true,
      },
      { label: "Media", key: "media", type: "file", required: false },
    ],
  },
  "Natural Heritage": {
    NaturalHeritageSite: [
      { label: "Site Name", key: "siteName", type: "text", required: true },
      { label: "Media", key: "media", type: "file", required: false },
      {
        label: "Description",
        key: "description",
        type: "textarea",
        required: false,
      },
      {
        label: "Ecological Significance",
        key: "ecologicalSignificance",
        type: "textarea",
        required: false,
      },
      {
        label: "Visiting Information",
        key: "visitingInformation",
        type: "textarea",
        required: false,
      },
      {
        label: "Contact Information",
        key: "contactInformation",
        type: "text",
        required: false,
      },
      { label: "Location", key: "location", type: "text", required: false },
    ],
    ConservationistAndNaturalist: [
      { label: "Occupation", key: "occupation", type: "text", required: false },
      {
        label: "Biography",
        key: "biography",
        type: "textarea",
        required: false,
      },
      {
        label: "Areas of Expertise",
        key: "areasOfExpertise",
        type: "text",
        required: false,
      },
      { label: "Location", key: "location", type: "text", required: false },
      {
        label: "Contact Information",
        key: "contactInformation",
        type: "text",
        required: false,
      },
      { label: "Media", key: "media", type: "file", required: false },
    ],
    wildlifeReservesAndNationalPark: [
      { label: "Name", key: "name", type: "text", required: true },
      { label: "Type", key: "type", type: "text", required: false },
      { label: "Location", key: "location", type: "text", required: false },
      {
        label: "Flora and Fauna",
        key: "floraAndFauna",
        type: "textarea",
        required: false,
      },
      {
        label: "Visitor Information",
        key: "visitorInformation",
        type: "textarea",
        required: false,
      },
      {
        label: "Contact Information",
        key: "contactInformation",
        type: "text",
        required: false,
      },
      { label: "Media", key: "media", type: "file", required: false },
    ],
    EnvironmentalEducationAndOutreach: [
      {
        label: "Organization Name",
        key: "organizationName",
        type: "text",
        required: true,
      },
      { label: "Focus Area", key: "focusArea", type: "text", required: false },
      { label: "Location", key: "location", type: "text", required: false },
      { label: "Programs", type: "textarea", required: false },
      {
        label: "Upcoming Events",
        key: "upcomingEvents",
        type: "text",
        required: false,
      },
      {
        label: "Contact Information",
        key: "contactInformation",
        type: "text",
        required: false,
      },
      { label: "Media", key: "media", type: "file", required: false },
    ],
  },
  "Recreation and Leisure": {
    ParksAndOutdoorActivities: [
      {
        label: "Location Name",
        key: "location_name",
        type: "text",
        required: true,
      },
      { label: "Type", key: "type", type: "text", required: true },
      { label: "Location", key: "location", type: "text", required: true },
      {
        label: "Description",
        key: "description",
        type: "textarea",
        required: true,
      },
      {
        label: "Facilities",
        key: "facilities",
        type: "textarea",
        required: true,
      },
      {
        label: "Contact Information",
        key: "contact_information",
        type: "text",
        required: true,
      },
      { label: "Media", key: "media", type: "file", required: false },
    ],
    SportsAndRecreationActivities: [
      {
        label: "Facility Name",
        key: "facility_name",
        type: "text",
        required: true,
      },
      { label: "Type", key: "type", type: "text", required: true },
      { label: "Location", key: "location", type: "text", required: true },
      {
        label: "Available Activities",
        key: "available_activities",
        type: "textarea",
        required: true,
      },
      {
        label: "Operating Hours",
        key: "operating_hours",
        type: "text",
        required: true,
      },
      {
        label: "Contact Information",
        key: "contact_information",
        type: "text",
        required: true,
      },
      { label: "Media", key: "media", type: "file", required: false },
    ],
    EntertainmentVenues: [
      { label: "Venue Name", key: "venue_name", type: "text", required: true },
      { label: "Type", key: "type", type: "text", required: true },
      { label: "Location", key: "location", type: "text", required: true },
      {
        label: "Upcoming Events",
        key: "upcoming_events",
        type: "textarea",
        required: true,
      },
      {
        label: "Ticketing Information",
        key: "ticketing_information",
        type: "textarea",
        required: true,
      },
      {
        label: "Contact Information",
        key: "contact_information",
        type: "text",
        required: true,
      },
      { label: "Media", key: "media", type: "file", required: false },
    ],
    LeisureActivitiesAndClasses: [
      {
        label: "Activity Name",
        key: "activity_name",
        type: "text",
        required: true,
      },
      { label: "Location", key: "location", type: "text", required: true },
      {
        label: "Description",
        key: "description",
        type: "textarea",
        required: true,
      },
      { label: "Schedule", key: "schedule", type: "textarea", required: true },
      {
        label: "Instructors",
        key: "instructors",
        type: "textarea",
        required: true,
      },
      {
        label: "Contact Information",
        key: "contact_information",
        type: "text",
        required: true,
      },
      { label: "Media", key: "media", type: "file", required: false },
    ],
  },
};
