export const digitalEthnographyForms = {
  ArchitectureAndConstruction: [
    {
      label: "Tribe",
      key: "tribe_id",
      type: "select",
      required: true,
      options: [],
    },
    {
      label: "Architectural Styles",
      key: "architectural_styles",
      type: "textarea",
      required: true,
    },
    {
      label: "Building Techniques",
      key: "building_techniques",
      type: "textarea",
      required: true,
    },
    {
      label: "Cultural Significance",
      key: "cultural_significance",
      type: "textarea",
      required: true,
    },
    { label: "Media", key: "media", type: "file", required: false },
  ],
  DietaryCulinaryPractices: [
    {
      label: "Tribe",
      key: "tribe_id",
      type: "select",
      required: true,
      options: [],
    },
    {
      label: "Culinary Heritage",
      key: "CulinaryHeritage",
      type: "textarea",
      required: true,
    },
    { label: "Recipes", key: "Recipes", type: "textarea", required: true },
    {
      label: "Food Significance",
      key: "FoodSignificance",
      type: "textarea",
      required: true,
    },
    { label: "Media", key: "media", type: "file", required: false },
  ],
  EconomicValuesAndCommerce: [
    {
      label: "Tribe",
      key: "tribe_id",
      type: "select",
      required: true,
      options: [],
    },
    {
      label: "Economic Practices",
      key: "EconomicPractices",
      type: "textarea",
      required: true,
    },
    {
      label: "Trade Networks",
      key: "TradeNetworks",
      type: "textarea",
      required: true,
    },
    {
      label: "Value Systems",
      key: "ValueSystems",
      type: "textarea",
      required: true,
    },
    { label: "Media", key: "media", type: "file", required: false },
  ],
  EducationAndArts: [
    {
      label: "Tribe",
      key: "tribe_id",
      type: "select",
      required: true,
      options: [],
    },
    {
      label: "Education Approach",
      key: "EducationApproach",
      type: "textarea",
      required: true,
    },
    {
      label: "Artistic Expressions",
      key: "ArtisticExpressions",
      type: "textarea",
      required: true,
    },
    { label: "Media", key: "media", type: "file", required: false },
  ],
  EntertainmentAndRecreation: [
    {
      label: "Tribe",
      key: "tribe_id",
      type: "select",
      required: true,
      options: [],
    },
    {
      label: "Cultural Forms",
      key: "CulturalForms",
      type: "textarea",
      required: true,
    },
    {
      label: "Leisure Activities",
      key: "LeisureActivities",
      type: "textarea",
      required: true,
    },
    {
      label: "Celebrations",
      key: "Celebrations",
      type: "textarea",
      required: true,
    },
    { label: "Media", key: "media", type: "file", required: false },
  ],
  Folklore: [
    {
      label: "Tribe",
      key: "tribe_id",
      type: "select",
      required: true,
      options: [],
    },
    { label: "Myths", key: "Myths", type: "textarea", required: true },
    { label: "Legends", key: "Legends", type: "textarea", required: true },
    { label: "Stories", key: "Stories", type: "textarea", required: true },
    { label: "Media", key: "media", type: "file", required: false },
  ],
  HealthAndWellness: [
    {
      label: "Tribe",
      key: "tribe_id",
      type: "select",
      required: true,
      options: [],
    },
    {
      label: "Healthcare Practices",
      key: "HealthcarePractices",
      type: "textarea",
      required: true,
    },
    { label: "Remedies", key: "Remedies", type: "textarea", required: true },
    {
      label: "WellBeingPerspectives",
      key: "WellBeingPerspectives",
      type: "textarea",
      required: true,
    },
    { label: "Media", key: "media", type: "file", required: false },
  ],
  Language: [
    {
      label: "Tribe",
      key: "tribe_id",
      type: "select",
      required: true,
      options: [],
    },
    {
      label: "Tribe Language",
      key: "TribeLanguage",
      type: "text",
      required: true,
    },
    {
      label: "Linguistic Nuances",
      key: "LinguisticNuances",
      type: "textarea",
      required: true,
    },

    { label: "Media", key: "media", type: "file", required: false },
  ],
  LeadershipAndGovernance: [
    {
      label: "Tribe",
      key: "tribe_id",
      type: "select",
      required: true,
      options: [],
    },
    {
      label: "Leadership Systems",
      key: "LeadershipSystems",
      type: "textarea",
      required: true,
    },
    {
      label: "Decision Making",
      key: "DecisionMaking",
      type: "textarea",
      required: true,
    },

    { label: "Media", key: "media", type: "file", required: false },
  ],
  LegalJusticeSystem: [
    {
      label: "Tribe",
      key: "tribe_id",
      type: "select",
      required: true,
      options: [],
    },
    {
      label: "Legal Practices",
      key: "LegalPractices",
      type: "textarea",
      required: true,
    },
    {
      label: "Conflict Resolution",
      key: "ConflictResolution",
      type: "textarea",
      required: true,
    },

    { label: "Media", key: "media", type: "file", required: false },
  ],
  ReligiousAndSpiritualPractices: [
    {
      label: "Tribe",
      key: "tribe_id",
      type: "select",
      required: true,
      options: [],
    },
    {
      label: "Beliefs",
      key: "Beliefs",
      type: "text",
      required: true,
    },
    {
      label: "Rituals",
      key: "Rituals",
      type: "textarea",
      required: true,
    },
    {
      label: "Spiritual Leaders",
      key: "SpiritualLeaders",
      type: "textarea",
      required: true,
    },
    { label: "Media", key: "media", type: "file", required: false },
  ],
  SecurityAndDefence: [
    {
      label: "Tribe",
      key: "tribe_id",
      type: "select",
      required: true,
      options: [],
    },
    {
      label: "Defense Mechanisms",
      key: "DefenseMechanisms",
      type: "textarea",
      required: true,
    },
    {
      label: "Strategies",
      key: "Strategies",
      type: "textarea",
      required: true,
    },

    { label: "Media", key: "media", type: "file", required: false },
  ],
  SocialRelations: [
    {
      label: "Tribe",
      key: "tribe_id",
      type: "select",
      required: true,
      options: [],
    },
    {
      label: "Social Structures",
      key: "SocialStructures",
      type: "textarea",
      required: true,
    },
    {
      label: "Norms",
      key: "Norms",
      type: "text",
      required: true,
    },
    {
      label: "Interpersonal Dynamics",
      key: "InterpersonalDynamics",
      type: "textarea",
      required: true,
    },
    { label: "Media", key: "media", type: "file", required: false },
  ],
  "Tangible Heritage": {
    CulturalIndustries: [
      {
        label: "Tribe",
        key: "tribe_id",
        type: "select",
        required: true,
        options: [],
      },
      {
        label: "Artistic Endeavors",
        key: "ArtisticEndeavors",
        type: "textarea",
        required: true,
      },
      { label: "Crafts", key: "Crafts", type: "textarea", required: true },
      {
        label: "Productions",
        key: "Productions",
        type: "textarea",
        required: true,
      },
      { label: "Media", key: "media", type: "file", required: false },
    ],
    CulturalCommunityOrganizations: [
      {
        label: "Tribe",
        key: "tribe_id",
        type: "select",
        required: true,
        options: [],
      },
      {
        label: "Cultural Organizations",
        key: "CulturalOrganizations",
        type: "textarea",
        required: true,
      },
      {
        label: "Community Cohesion",
        key: "CommunityCohesion",
        type: "textarea",
        required: true,
      },
    ],
    CulturalFacilitiesSpaces: [
      {
        label: "Tribe",
        key: "tribe_id",
        type: "select",
        required: true,
        options: [],
      },
      {
        label: "Cultural Spaces",
        key: "CulturalSpaces",
        type: "textarea",
        required: true,
      },
      {
        label: "Facilities Description",
        key: "FacilitiesDescription",
        type: "textarea",
        required: true,
      },
    ],
    HeritagePlaces: [
      {
        label: "Tribe",
        key: "tribe_id",
        type: "select",
        required: true,
        options: [],
      },
      {
        label: "Places of Significance",
        key: "PlacesOfSignificance",
        type: "textarea",
        required: true,
      },
      {
        label: "Memory and Meaning",
        key: "MemoryAndMeaning",
        type: "textarea",
        required: true,
      },
    ],
    NaturalHeritage: [
      {
        label: "Tribe",
        key: "tribe_id",
        type: "select",
        required: true,
        options: [],
      },
      {
        label: "Environmental Practices",
        key: "EnvironmentalPractices",
        type: "textarea",
        required: true,
      },
      {
        label: "Stewardship",
        key: "Stewardship",
        type: "textarea",
        required: true,
      },
    ],
    CreativeCulturalOccupations: [
      {
        label: "Tribe",
        key: "tribe_id",
        type: "select",
        required: true,
        options: [],
      },
      {
        label: "Cultural Occupations",
        key: "CulturalOccupations",
        type: "textarea",
        required: true,
      },
      { label: "Artisans", key: "Artisans", type: "textarea", required: true },
      {
        label: "Storytellers",
        key: "Storytellers",
        type: "textarea",
        required: true,
      },
    ],
  },
  "Tribe Overview": {
    Tribe: [
      {
        label: "Tribe Name",
        key: "tribe_name",
        type: "text",
        required: true,
      },
      { label: "Etymology", key: "etymology", type: "text", required: true },
    ],
    PopulationDemographics: [
      {
        label: "Tribe",
        key: "tribe_id",
        type: "select",
        required: true,
        options: [],
      },
      {
        label: "Current Population",
        key: "current_population",
        type: "number",
        required: true,
      },
      {
        label: "Demographic Trends",
        key: "demographic_trends",
        type: "text",
        required: true,
      },
      {
        label: "Distribution",
        key: "distribution",
        type: "text",
        required: false,
      },
    ],
    History: [
      {
        label: "Tribe",
        key: "tribe_id",
        type: "select",
        required: true,
        options: [],
      },
      {
        label: "Historical Events",
        key: "historical_events",
        type: "text",
        required: true,
      },
      {
        label: "Migrations",
        key: "migrations",
        type: "text",
        required: true,
      },
      {
        label: "Interactions",
        key: "interactions",
        type: "text",
        required: true,
      },
    ],
  },
};
